-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		MICHEL ROBERTO TRAÑA TABLADA
-- Create date: 12/07/2016
-- Description:	ESTE PROCEDIMIENTO ALMACENADO PERMITE SELECCIONAR EL LISTADO DE PRODUCTOS VENDIDOS EN UN RANGO DE TIEMPO
-- =============================================
CREATE PROCEDURE SpProductosComprados
	-- Add the parameters for the stored procedure here
@Inicio AS DATETIME,
@Final AS DATETIME,
@IDBodega AS VARCHAR(36),
@IDSerie AS VARCHAR(36),
@NEmpleado AS VARCHAR(50),
@Empleado AS VARCHAR(100),
@NProveedor AS VARCHAR(50),
@Proveedor AS VARCHAR(100),
@TipoCOMPRA AS INTEGER,
@MonInv AS Bit,
@Taza AS DECIMAL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	--DECLARAR VARIABLES DE TAZA DE CAMBIO
	DECLARE @TazaCordoba AS DECIMAL(18,4)
	DECLARE @TazaDolar AS DECIMAL(18,4)
	IF @MonInv = 1
		BEGIN
			SET @TazaCordoba = 1
			SET @TazaDolar = @Taza
		END
	ELSE
		BEGIN
			SET @TazaDolar = 1
			SET @TazaCordoba = @Taza
		END
	-- 1. SELECCIONAR TODOS LOS DATOS
	IF @TipoCOMPRA <> 1 AND @TipoCOMPRA <> 2
	BEGIN
		(SELECT 
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) / SUM(COMPRA_DETALLE.CANTIDAD) AS PrecioPromedio,
			SUM(COMPRA_DETALLE.CANTIDAD) AS Cantidad,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_D * @TazaDolar)) AS Descuento,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) AS SubTotal,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.IVA_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.IVA_DIN_TOTAL_D * @TazaDolar)) AS Iva,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.TOTAL_C / @TazaCordoba, COMPRA_DETALLE.TOTAL_D * @TazaDolar)) AS Total,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar) - (COMPRA_DETALLE.COSTO * COMPRA_DETALLE.CANTIDAD)) AS Utilidad
		FROM
			PRODUCTO
			INNER JOIN EXISTENCIA ON PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
			INNER JOIN COMPRA_DETALLE ON EXISTENCIA.IDEXISTENCIA = COMPRA_DETALLE.IDEXISTENCIA
			INNER JOIN COMPRA ON COMPRA_DETALLE.IDCOMPRA = COMPRA.IDCOMPRA
			INNER JOIN EMPLEADO ON COMPRA.IDEMPLEADO = EMPLEADO.IDEMPLEADO
			INNER JOIN CLIENTE ON COMPRA.IDCLIENTE = CLIENTE.IDCLIENTE
			INNER JOIN SERIE ON COMPRA.IDSERIE = SERIE.IDSERIE
			INNER JOIN BODEGA ON SERIE.IDBODEGA = BODEGA.IDBODEGA
		WHERE
			COMPRA.ANULADO = 'N'
			AND COMPRA.FECHACOMPRA >= @INICIO
			AND COMPRA.FECHACOMPRA <= @FINAL
			AND BODEGA.IDBODEGA LIKE (@IDBODEGA + '%')
			AND SERIE.IDSERIE LIKE (@IDSERIE + '%')
			AND EMPLEADO.N_TRABAJADOR LIKE (@NEmpleado + '%')
			AND (EMPLEADO.NOMBRES + ' ' + EMPLEADO.APELLIDOS) LIKE (@Empleado + '%')
			AND CLIENTE.N_CLIENTE LIKE (@NProveedor + '%')
			AND (CLIENTE.NOMBRES + ' ' + CLIENTE.APELLIDOS) LIKE (@Proveedor + '%')
		GROUP BY
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION)
	UNION
		(SELECT 
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) / SUM(COMPRA_DETALLE.CANTIDAD) AS PrecioPromedio,
			SUM(COMPRA_DETALLE.CANTIDAD) AS Cantidad,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_D * @TazaDolar)) AS Descuento,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) AS SubTotal,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.IVA_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.IVA_DIN_TOTAL_D * @TazaDolar)) AS Iva,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.TOTAL_C / @TazaCordoba, COMPRA_DETALLE.TOTAL_D * @TazaDolar)) AS Total,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar) - (COMPRA_DETALLE.COSTO * COMPRA_DETALLE.CANTIDAD)) AS Utilidad
		FROM
			PRODUCTO
			INNER JOIN EXISTENCIA ON PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
			INNER JOIN COMPRA_DETALLE ON EXISTENCIA.IDEXISTENCIA = COMPRA_DETALLE.IDEXISTENCIA
			INNER JOIN COMPRA ON COMPRA_DETALLE.IDCOMPRA = COMPRA.IDCOMPRA
			INNER JOIN EMPLEADO ON COMPRA.IDEMPLEADO = EMPLEADO.IDEMPLEADO
			INNER JOIN SERIE ON COMPRA.IDSERIE = SERIE.IDSERIE
			INNER JOIN BODEGA ON SERIE.IDBODEGA = BODEGA.IDBODEGA
		WHERE
			COMPRA.ANULADO = 'N'
			AND COMPRA.IDCLIENTE IS NULL
			AND COMPRA.FECHACOMPRA >= @INICIO
			AND COMPRA.FECHACOMPRA <= @FINAL
			AND BODEGA.IDBODEGA LIKE (@IDBODEGA + '%')
			AND SERIE.IDSERIE LIKE (@IDSERIE + '%')
			AND EMPLEADO.N_TRABAJADOR LIKE (@NEmpleado + '%')
			AND (EMPLEADO.NOMBRES + ' ' + EMPLEADO.APELLIDOS) LIKE (@Empleado + '%')
			AND RTRIM(@NProveedor) = ('')
			AND (COMPRA.CLIENTECONTADO) LIKE (@Proveedor + '%')
		GROUP BY
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION)
	END






	--2. SELECCIONAR COMPRAS DE CONTADO
	IF @TipoCOMPRA = 1
	BEGIN
		(SELECT 
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) / SUM(COMPRA_DETALLE.CANTIDAD) AS PrecioPromedio,
			SUM(COMPRA_DETALLE.CANTIDAD) AS Cantidad,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_D * @TazaDolar)) AS Descuento,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) AS SubTotal,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.IVA_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.IVA_DIN_TOTAL_D * @TazaDolar)) AS Iva,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.TOTAL_C / @TazaCordoba, COMPRA_DETALLE.TOTAL_D * @TazaDolar)) AS Total,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar) - (COMPRA_DETALLE.COSTO * COMPRA_DETALLE.CANTIDAD)) AS Utilidad
		FROM
			PRODUCTO
			INNER JOIN EXISTENCIA ON PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
			INNER JOIN COMPRA_DETALLE ON EXISTENCIA.IDEXISTENCIA = COMPRA_DETALLE.IDEXISTENCIA
			INNER JOIN COMPRA ON COMPRA_DETALLE.IDCOMPRA = COMPRA.IDCOMPRA
			INNER JOIN EMPLEADO ON COMPRA.IDEMPLEADO = EMPLEADO.IDEMPLEADO
			INNER JOIN CLIENTE ON COMPRA.IDCLIENTE = CLIENTE.IDCLIENTE
			INNER JOIN SERIE ON COMPRA.IDSERIE = SERIE.IDSERIE
			INNER JOIN BODEGA ON SERIE.IDBODEGA = BODEGA.IDBODEGA
		WHERE
			COMPRA.ANULADO = 'N'
			AND COMPRA.FECHACOMPRA >= @INICIO
			AND COMPRA.FECHACOMPRA <= @FINAL
			AND BODEGA.IDBODEGA LIKE (@IDBODEGA + '%')
			AND SERIE.IDSERIE LIKE (@IDSERIE + '%')
			AND EMPLEADO.N_TRABAJADOR LIKE (@NEmpleado + '%')
			AND (EMPLEADO.NOMBRES + ' ' + EMPLEADO.APELLIDOS) LIKE (@Empleado + '%')
			AND CLIENTE.N_CLIENTE LIKE (@NProveedor + '%')
			AND (CLIENTE.NOMBRES + ' ' + CLIENTE.APELLIDOS) LIKE (@Proveedor + '%')
			AND COMPRA.CREDITO = 0
		GROUP BY
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION)
	UNION
		(SELECT 
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) / SUM(COMPRA_DETALLE.CANTIDAD) AS PrecioPromedio,
			SUM(COMPRA_DETALLE.CANTIDAD) AS Cantidad,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_D * @TazaDolar)) AS Descuento,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) AS SubTotal,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.IVA_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.IVA_DIN_TOTAL_D * @TazaDolar)) AS Iva,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.TOTAL_C / @TazaCordoba, COMPRA_DETALLE.TOTAL_D * @TazaDolar)) AS Total,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar) - (COMPRA_DETALLE.COSTO * COMPRA_DETALLE.CANTIDAD)) AS Utilidad
		FROM
			PRODUCTO
			INNER JOIN EXISTENCIA ON PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
			INNER JOIN COMPRA_DETALLE ON EXISTENCIA.IDEXISTENCIA = COMPRA_DETALLE.IDEXISTENCIA
			INNER JOIN COMPRA ON COMPRA_DETALLE.IDCOMPRA = COMPRA.IDCOMPRA
			INNER JOIN EMPLEADO ON COMPRA.IDEMPLEADO = EMPLEADO.IDEMPLEADO
			INNER JOIN SERIE ON COMPRA.IDSERIE = SERIE.IDSERIE
			INNER JOIN BODEGA ON SERIE.IDBODEGA = BODEGA.IDBODEGA
		WHERE
			COMPRA.ANULADO = 'N'
			AND COMPRA.IDCLIENTE IS NULL
			AND COMPRA.FECHACOMPRA >= @INICIO
			AND COMPRA.FECHACOMPRA <= @FINAL
			AND BODEGA.IDBODEGA LIKE (@IDBODEGA + '%')
			AND SERIE.IDSERIE LIKE (@IDSERIE + '%')
			AND EMPLEADO.N_TRABAJADOR LIKE (@NEmpleado + '%')
			AND (EMPLEADO.NOMBRES + ' ' + EMPLEADO.APELLIDOS) LIKE (@Empleado + '%')
			AND RTRIM(@NProveedor) = ('')
			AND (COMPRA.CLIENTECONTADO) LIKE (@Proveedor + '%')
			AND COMPRA.CREDITO = 0
		GROUP BY
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION)
	END






	--3. SELECCIONAR COMPRAS DE CREDITO
	IF @TipoCOMPRA = 2
	BEGIN
		(SELECT 
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) / SUM(COMPRA_DETALLE.CANTIDAD) AS PrecioPromedio,
			SUM(COMPRA_DETALLE.CANTIDAD) AS Cantidad,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.DESCUENTO_DIN_TOTAL_D * @TazaDolar)) AS Descuento,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar)) AS SubTotal,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.IVA_DIN_TOTAL_C / @TazaCordoba, COMPRA_DETALLE.IVA_DIN_TOTAL_D * @TazaDolar)) AS Iva,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.TOTAL_C / @TazaCordoba, COMPRA_DETALLE.TOTAL_D * @TazaDolar)) AS Total,
			SUM(IIF(COMPRA.MONEDA = 'C', COMPRA_DETALLE.SUBTOTAL_C / @TazaCordoba, COMPRA_DETALLE.SUBTOTAL_D * @TazaDolar) - (COMPRA_DETALLE.COSTO * COMPRA_DETALLE.CANTIDAD)) AS Utilidad
		FROM
			PRODUCTO
			INNER JOIN EXISTENCIA ON PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
			INNER JOIN COMPRA_DETALLE ON EXISTENCIA.IDEXISTENCIA = COMPRA_DETALLE.IDEXISTENCIA
			INNER JOIN COMPRA ON COMPRA_DETALLE.IDCOMPRA = COMPRA.IDCOMPRA
			INNER JOIN EMPLEADO ON COMPRA.IDEMPLEADO = EMPLEADO.IDEMPLEADO
			INNER JOIN CLIENTE ON COMPRA.IDCLIENTE = CLIENTE.IDCLIENTE
			INNER JOIN SERIE ON COMPRA.IDSERIE = SERIE.IDSERIE
			INNER JOIN BODEGA ON SERIE.IDBODEGA = BODEGA.IDBODEGA
		WHERE
			COMPRA.ANULADO = 'N'
			AND COMPRA.FECHACOMPRA >= @INICIO
			AND COMPRA.FECHACOMPRA <= @FINAL
			AND BODEGA.IDBODEGA LIKE (@IDBODEGA + '%')
			AND SERIE.IDSERIE LIKE (@IDSERIE + '%')
			AND EMPLEADO.N_TRABAJADOR LIKE (@NEmpleado + '%')
			AND (EMPLEADO.NOMBRES + ' ' + EMPLEADO.APELLIDOS) LIKE (@Empleado + '%')
			AND CLIENTE.N_CLIENTE LIKE (@NProveedor + '%')
			AND (CLIENTE.NOMBRES + ' ' + CLIENTE.APELLIDOS) LIKE (@Proveedor + '%')
			AND COMPRA.CREDITO = 1
		GROUP BY
			PRODUCTO.IDALTERNO,
			PRODUCTO.DESCRIPCION)
	END
	--FIN DEL STATEMENT


END
GO