DECLARE @INICIO DATETIME = '2016/01/01'
DECLARE @FINAL DATETIME = '2016/12/31'
DECLARE @IDBODEGA VARCHAR(30) = ''
DECLARE @IDSERIE VARCHAR(30) = ''
DECLARE @NEMPLEADO VARCHAR(50) = ''
DECLARE @EMPLEADO VARCHAR(50) = ''
DECLARE @NCLIENTE VARCHAR(50) = ''
DECLARE @CLIENTE VARCHAR(50) = ''

	(SELECT 
		PRODUCTO.IDALTERNO,
		PRODUCTO.DESCRIPCION,
		SUM(DETALLE_VENTA.COSTO * DETALLE_VENTA.CANTIDAD) / SUM(DETALLE_VENTA.CANTIDAD) AS CostoPromedio,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.SUBTOTAL_C, DETALLE_VENTA.SUBTOTAL_D * 28.70)) / SUM(DETALLE_VENTA.CANTIDAD) AS PrecioPromedio,
		SUM(DETALLE_VENTA.CANTIDAD) AS Cantidad,
		SUM(DETALLE_VENTA.COSTO * DETALLE_VENTA.CANTIDAD) AS CostoTotal,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.DESCUENTO_DIN_TOTAL_C, DETALLE_VENTA.DESCUENTO_DIN_TOTAL_D * 28.80)) AS Descuento,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.SUBTOTAL_C, DETALLE_VENTA.SUBTOTAL_D * 28.80)) AS SubTotal,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.IVA_DIN_TOTAL_C, DETALLE_VENTA.IVA_DIN_TOTAL_D * 28.80)) AS Iva,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.TOTAL_C, DETALLE_VENTA.TOTAL_D * 28.80)) AS Total,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.SUBTOTAL_C, DETALLE_VENTA.SUBTOTAL_D * 28.80) - (DETALLE_VENTA.COSTO * DETALLE_VENTA.CANTIDAD)) AS Utilidad
	FROM
		PRODUCTO
		INNER JOIN EXISTENCIA ON PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
		INNER JOIN DETALLE_VENTA ON EXISTENCIA.IDEXISTENCIA = DETALLE_VENTA.IDEXISTENCIA
		INNER JOIN VENTA ON DETALLE_VENTA.IDVENTA = VENTA.IDVENTA
		INNER JOIN EMPLEADO ON VENTA.IDEMPLEADO = EMPLEADO.IDEMPLEADO
		INNER JOIN CLIENTE ON VENTA.IDCLIENTE = CLIENTE.IDCLIENTE
		INNER JOIN SERIE ON VENTA.IDSERIE = SERIE.IDSERIE
		INNER JOIN BODEGA ON SERIE.IDBODEGA = BODEGA.IDBODEGA
	WHERE
		VENTA.ANULADO = 'N'
		AND VENTA.FECHAFACTURA >= @INICIO
		AND VENTA.FECHAFACTURA <= @FINAL
		AND BODEGA.IDBODEGA LIKE (@IDBODEGA + '%')
		AND SERIE.IDSERIE LIKE (@IDSERIE + '%')
		AND EMPLEADO.N_TRABAJADOR LIKE (@NEmpleado + '%')
		AND (EMPLEADO.NOMBRES + ' ' + EMPLEADO.APELLIDOS) LIKE (@Empleado + '%')
		AND CLIENTE.N_CLIENTE LIKE (@NCliente + '%')
		AND (CLIENTE.NOMBRES + ' ' + CLIENTE.APELLIDOS) LIKE (@Cliente + '%')
	GROUP BY
		PRODUCTO.IDALTERNO,
		PRODUCTO.DESCRIPCION)
UNION
	(SELECT 
		PRODUCTO.IDALTERNO,
		PRODUCTO.DESCRIPCION,
		SUM(DETALLE_VENTA.COSTO * DETALLE_VENTA.CANTIDAD) / SUM(DETALLE_VENTA.CANTIDAD) AS CostoPromedio,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.SUBTOTAL_C, DETALLE_VENTA.SUBTOTAL_D * 28.70)) / SUM(DETALLE_VENTA.CANTIDAD) AS PrecioPromedio,
		SUM(DETALLE_VENTA.CANTIDAD) AS Cantidad,
		SUM(DETALLE_VENTA.COSTO * DETALLE_VENTA.CANTIDAD) AS CostoTotal,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.DESCUENTO_DIN_TOTAL_C, DETALLE_VENTA.DESCUENTO_DIN_TOTAL_D * 28.80)) AS Descuento,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.SUBTOTAL_C, DETALLE_VENTA.SUBTOTAL_D * 28.80)) AS SubTotal,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.IVA_DIN_TOTAL_C, DETALLE_VENTA.IVA_DIN_TOTAL_D * 28.80)) AS Iva,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.TOTAL_C, DETALLE_VENTA.TOTAL_D * 28.80)) AS Total,
		SUM(IIF(VENTA.MONEDA = 'C', DETALLE_VENTA.SUBTOTAL_C, DETALLE_VENTA.SUBTOTAL_D * 28.80) - (DETALLE_VENTA.COSTO * DETALLE_VENTA.CANTIDAD)) AS Utilidad
	FROM
		PRODUCTO
		INNER JOIN EXISTENCIA ON PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
		INNER JOIN DETALLE_VENTA ON EXISTENCIA.IDEXISTENCIA = DETALLE_VENTA.IDEXISTENCIA
		INNER JOIN VENTA ON DETALLE_VENTA.IDVENTA = VENTA.IDVENTA
		INNER JOIN EMPLEADO ON VENTA.IDEMPLEADO = EMPLEADO.IDEMPLEADO
		INNER JOIN SERIE ON VENTA.IDSERIE = SERIE.IDSERIE
		INNER JOIN BODEGA ON SERIE.IDBODEGA = BODEGA.IDBODEGA
	WHERE
		VENTA.ANULADO = 'N'
		AND VENTA.IDCLIENTE IS NULL
		AND VENTA.FECHAFACTURA >= @INICIO
		AND VENTA.FECHAFACTURA <= @FINAL
		AND BODEGA.IDBODEGA LIKE (@IDBODEGA + '%')
		AND SERIE.IDSERIE LIKE (@IDSERIE + '%')
		AND EMPLEADO.N_TRABAJADOR LIKE (@NEmpleado + '%')
		AND (EMPLEADO.NOMBRES + ' ' + EMPLEADO.APELLIDOS) LIKE (@Empleado + '%')
		AND RTRIM(@NCliente) = ('')
		AND (VENTA.CLIENTECONTADO) LIKE (@Cliente + '%')
	GROUP BY
		PRODUCTO.IDALTERNO,
		PRODUCTO.DESCRIPCION)


		--SELECT PRODUCTO.IDALTERNO, DETALLE_VENTA.COSTO, 
		--DETALLE_VENTA.PRECIOUNITARIO_C, DETALLE_VENTA.PRECIONETO_C, 
		--DETALLE_VENTA.CANTIDAD FROM PRODUCTO, EXISTENCIA, DETALLE_VENTA
		--WHERE PRODUCTO.IDPRODUCTO = EXISTENCIA.IDPRODUCTO
		--AND EXISTENCIA.IDEXISTENCIA = DETALLE_VENTA.IDEXISTENCIA
		--GO