'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicioProducto
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CatalogoProducto", [Namespace]:="http://schemas.datacontract.org/2004/07/Capadenegocio"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CatalogoProducto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AplicacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContieneField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdAlternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdOriginalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdProductoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IvaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LaboratorioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MarcaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModeloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Precio1Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Precio2Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Precio3Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Precio4Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PresentacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnidadDeMedidaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Aplicacion() As String
            Get
                Return Me.AplicacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AplicacionField, value) <> true) Then
                    Me.AplicacionField = value
                    Me.RaisePropertyChanged("Aplicacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Contiene() As Decimal
            Get
                Return Me.ContieneField
            End Get
            Set
                If (Me.ContieneField.Equals(value) <> true) Then
                    Me.ContieneField = value
                    Me.RaisePropertyChanged("Contiene")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdAlterno() As String
            Get
                Return Me.IdAlternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdAlternoField, value) <> true) Then
                    Me.IdAlternoField = value
                    Me.RaisePropertyChanged("IdAlterno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdOriginal() As String
            Get
                Return Me.IdOriginalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdOriginalField, value) <> true) Then
                    Me.IdOriginalField = value
                    Me.RaisePropertyChanged("IdOriginal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdProducto() As String
            Get
                Return Me.IdProductoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdProductoField, value) <> true) Then
                    Me.IdProductoField = value
                    Me.RaisePropertyChanged("IdProducto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageName() As String
            Get
                Return Me.ImageNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageNameField, value) <> true) Then
                    Me.ImageNameField = value
                    Me.RaisePropertyChanged("ImageName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Iva() As Boolean
            Get
                Return Me.IvaField
            End Get
            Set
                If (Me.IvaField.Equals(value) <> true) Then
                    Me.IvaField = value
                    Me.RaisePropertyChanged("Iva")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Laboratorio() As String
            Get
                Return Me.LaboratorioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LaboratorioField, value) <> true) Then
                    Me.LaboratorioField = value
                    Me.RaisePropertyChanged("Laboratorio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Marca() As String
            Get
                Return Me.MarcaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MarcaField, value) <> true) Then
                    Me.MarcaField = value
                    Me.RaisePropertyChanged("Marca")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Modelo() As String
            Get
                Return Me.ModeloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModeloField, value) <> true) Then
                    Me.ModeloField = value
                    Me.RaisePropertyChanged("Modelo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observacion() As String
            Get
                Return Me.ObservacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionField, value) <> true) Then
                    Me.ObservacionField = value
                    Me.RaisePropertyChanged("Observacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Precio1() As Decimal
            Get
                Return Me.Precio1Field
            End Get
            Set
                If (Me.Precio1Field.Equals(value) <> true) Then
                    Me.Precio1Field = value
                    Me.RaisePropertyChanged("Precio1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Precio2() As Decimal
            Get
                Return Me.Precio2Field
            End Get
            Set
                If (Me.Precio2Field.Equals(value) <> true) Then
                    Me.Precio2Field = value
                    Me.RaisePropertyChanged("Precio2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Precio3() As Decimal
            Get
                Return Me.Precio3Field
            End Get
            Set
                If (Me.Precio3Field.Equals(value) <> true) Then
                    Me.Precio3Field = value
                    Me.RaisePropertyChanged("Precio3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Precio4() As Decimal
            Get
                Return Me.Precio4Field
            End Get
            Set
                If (Me.Precio4Field.Equals(value) <> true) Then
                    Me.Precio4Field = value
                    Me.RaisePropertyChanged("Precio4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Presentacion() As String
            Get
                Return Me.PresentacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PresentacionField, value) <> true) Then
                    Me.PresentacionField = value
                    Me.RaisePropertyChanged("Presentacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UnidadDeMedida() As String
            Get
                Return Me.UnidadDeMedidaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UnidadDeMedidaField, value) <> true) Then
                    Me.UnidadDeMedidaField = value
                    Me.RaisePropertyChanged("UnidadDeMedida")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioProducto.IProducto")>  _
    Public Interface IProducto
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProducto/Listado", ReplyAction:="http://tempuri.org/IProducto/ListadoResponse")>  _
        Function Listado(ByVal IdAlterno As String, ByVal IdOriginal As String, ByVal Descripcion As String, ByVal Aplicacion As String) As ServicioProducto.CatalogoProducto()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProducto/Listado", ReplyAction:="http://tempuri.org/IProducto/ListadoResponse")>  _
        Function ListadoAsync(ByVal IdAlterno As String, ByVal IdOriginal As String, ByVal Descripcion As String, ByVal Aplicacion As String) As System.Threading.Tasks.Task(Of ServicioProducto.CatalogoProducto())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProducto/Nuevo", ReplyAction:="http://tempuri.org/IProducto/NuevoResponse")>  _
        Function Nuevo() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProducto/Nuevo", ReplyAction:="http://tempuri.org/IProducto/NuevoResponse")>  _
        Function NuevoAsync() As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IProductoChannel
        Inherits ServicioProducto.IProducto, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ProductoClient
        Inherits System.ServiceModel.ClientBase(Of ServicioProducto.IProducto)
        Implements ServicioProducto.IProducto
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Listado(ByVal IdAlterno As String, ByVal IdOriginal As String, ByVal Descripcion As String, ByVal Aplicacion As String) As ServicioProducto.CatalogoProducto() Implements ServicioProducto.IProducto.Listado
            Return MyBase.Channel.Listado(IdAlterno, IdOriginal, Descripcion, Aplicacion)
        End Function
        
        Public Function ListadoAsync(ByVal IdAlterno As String, ByVal IdOriginal As String, ByVal Descripcion As String, ByVal Aplicacion As String) As System.Threading.Tasks.Task(Of ServicioProducto.CatalogoProducto()) Implements ServicioProducto.IProducto.ListadoAsync
            Return MyBase.Channel.ListadoAsync(IdAlterno, IdOriginal, Descripcion, Aplicacion)
        End Function
        
        Public Function Nuevo() As Boolean Implements ServicioProducto.IProducto.Nuevo
            Return MyBase.Channel.Nuevo
        End Function
        
        Public Function NuevoAsync() As System.Threading.Tasks.Task(Of Boolean) Implements ServicioProducto.IProducto.NuevoAsync
            Return MyBase.Channel.NuevoAsync
        End Function
    End Class
End Namespace
